### ISSUE TITLE
heterogeneous graphs

### ISSUE THREAD

**Issue by jpata** [jpata/particleflow#101]
For the moment, we concatenate input elements of different types (tracks, clusters, ...) into a single feature matrix. This means that there are features that may be defined for one type, but not defined for other types. Our ML model downstream treats all input elements as nodes of the same type. In principle, splitting up the inputs from a single feature matrix to independent feature matrices for each element type should be better.

**Comment by jmduarte** [comment]
Along these lines, we can use the approach ParticleNet uses where basically each input set (in that case particles, and secondary vertices; in our case tracks and clusters) are first put through their own MLP 

https://github.com/hqucms/weaver/blob/master/utils/nn/model/ParticleNet.py#L253-L254

**Comment by jpata** [comment]
Now we can try this out in pytorch: https://github.com/jpata/particleflow/issues/235
