### ISSUE TITLE
add a loss term wrt. genjet clustering

### ISSUE THREAD

**Issue by jpata** [jpata/particleflow#122]
We want to improve jet and MET resolution of MLPF, but these cannot directly be written into the loss function.
It was suggested by JD that we could cluster the gen-particles to jets and save the jet clustering index for each particle.

Since we have this one-to-one matching between genparticles, input elements and predicted particles, we can add a loss term where we compare jets from the predicted particles based on the genparticle clustering index to jets from the genparticles.

For the TF model, this would mean running fastjet at the tfds stage, saving the jet clustering index for each particle, propagating it to the loss function and adding an additional term.

**Comment by jmduarte** [comment]
Started here: https://github.com/jpata/hep_tfds/pull/4

**Comment by jpata** [comment]
Added in #126 and https://github.com/jpata/hep_tfds/pull/4. Thanks!
Next we need to make some comparisons.
