### ISSUE TITLE
pre-commit hook to run black, flake8, isort, etc.

### ISSUE THREAD

**Issue by jmduarte** [jpata/particleflow#128]
very low priority, but we could add a pre-commit hook to make run black, flake8, isort, etc on the repo to enforce common style and minimal diffs.

It could also run automatically to lint PRs, etc.. 

- pre-commit yaml: https://github.com/FAIR4HEP/hbb_interaction_network/blob/main/.pre-commit-config.yaml
- github action to lint PRs: https://github.com/FAIR4HEP/hbb_interaction_network/blob/main/.github/workflows/pre-commit.yml

**Comment by jpata** [comment]
yes, I've been wanting to clean up the code with black etc at a point when there is no big feature PR in the pipeline, and then make it a requirement via e.g. a hook. let's try to do it soon.

**Comment by jpata** [comment]
Addressing it in #129.
