### ISSUE TITLE
regressing multimodal distributions accurately

### ISSUE THREAD

**Issue by jpata** [jpata/particleflow#236]
Something Michael K said in the meeting about using simple regression for multimodal target distributions being a poor approximation and only able to predict the avergae.

I believe this could have a big effect, as we have many different particle types with different kinematic spectra (e.g. energy), yet the regression network is the same and just tries to predict a single value.

Need to find a good reference for this.

**Comment by jmduarte** [comment]
https://towardsdatascience.com/anchors-and-multi-bin-loss-for-multi-modal-target-regression-647ea1974617

Multi-bin loss is interesting

**Comment by jpata** [comment]
Despite my best efforts in https://github.com/jpata/particleflow/pull/234, in the end I have reverted the multi-bin / multimodal loss to simple regression in TF https://github.com/jpata/particleflow/pull/253, because despite promising initial checks, the final physics performance after a long training was not competitive.
