### ISSUE TITLE
Separate the regression "MLP" into "NUM_CLASSES*MLP"

### ISSUE THREAD

**Issue by farakiko** [jpata/particleflow#242]
instead of using the same MLP to regress the pt,eta,phi,e of the particles, we could use a seperate MLP depending on the classified label of the particle

**Comment by jpata** [comment]
This is now possible by changing to `pt_mode: linear-elemtype`, also for the other regression outputs.
https://github.com/jpata/particleflow/blob/5e13929e7c31a5134adaaf8966419396818eb986/parameters/pytorch/pyg-cms.yaml#L33-L37

implemented here:
https://github.com/jpata/particleflow/blob/5e13929e7c31a5134adaaf8966419396818eb986/mlpf/pyg/mlpf.py#L163-L168
