### ISSUE TITLE
Separate training of Classification and Regression

### ISSUE THREAD

**Issue by farakiko** [jpata/particleflow#243]
Run full classification-only training then freeze the model and run full regression. the idea is to minimize the interplay of minimizing two losses at the same time.

**Comment by jpata** [comment]
This is now possible by configuring `trainable` as in here:
https://github.com/jpata/particleflow/blob/main/parameters/pytorch/pyg-cms.yaml#L27-L29

One can freeze all layers except the pt/energy regression for example.
